version: "3.9"

volumes:
  tickets_db_volume:
  users_db_volume:

services:
  bot:
    build:
      context: .
      dockerfile: DockerfileBot
    restart: always
    environment:
      FLASK_ENV: development
    depends_on:
      - tickets_db
      - users_db

  tickets_db:
    build:
      context: .
      dockerfile: DockerfileTickets
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: tickets_db_mysql
      MYSQL_DATABASE: tickets
    depends_on:
      - tickets_db_mysql

  tickets_db_mysql:
     image: mysql
     restart: always
     environment:
       MYSQL_DATABASE: tickets
       MYSQL_ROOT_PASSWORD: password
     volumes:
       - tickets_db_volume:/var/lib/mysql

  users_db:
    build:
      context: .
      dockerfile: DockerfileUsers
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: users_db_mysql
      MYSQL_DATABASE: users
    depends_on:
      - users_db_mysql

  users_db_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - users_db_volume:/var/lib/mysql